language: python
python:
  - "2.7"
addons:
  apt:
    packages:
    - build-essential
    - cython
    - python-dev
    - libxslt1-dev
    - libxml2-dev
    - zlib1g-dev
    - libevent-dev
    - libffi-dev
    - libfreetype6-dev
    - liblcms2-dev
    - cmake
    - imagemagick
    - libssl-dev
    - libzmq-dev
    - libmysqlclient-dev
install:
  - make install
script:
  - python setup.py test